#!/bin/sh

wpctl get-volume @DEFAULT_SINK@ | awk '{
    # Remove "Volume: " prefix
    gsub(/Volume: /, "");
    
    # Extract numeric value (handles cases like "1.50" or "0.00 [MUTED]")
    if (match($0, /[0-9]+\.[0-9]+/)) {
        vol = substr($0, RSTART, RLENGTH);
        # Convert to percentage (multiply by 100, remove trailing .0)
        percentage = int(vol * 100) "%";
        # Replace the number with percentage
        sub(/[0-9]+\.[0-9]+/, percentage);
    }
    print $0
}'
